### ISSUE TITLE
[design]텍스트 생성 페이지 퍼블리싱

### ISSUE THREAD

**Issue by Seyeonnnn** [2024-Summer-BootCamp-TeamG/Team#20]
## :rocket: 참고할 만한 게 있을까요?
로고, 집 아이콘 빼고 만들기
## :memo: 참고 사항

- 제목 양식을 지켜주세요.

- [타입] 간단한 제목

- 제목은 알아보기 쉽게 작성해 주세요!

**Comment by 9JIIIIIN9** [comment]
FE/design/#20
